const DUMMY_LIST = [
	{
		id: "p1",
		title: "Дрель",
		brand: "Makita 18v",
		description:
			"Makita является инновационным лидером в области технологий бесщеточных двигателей, а бесщеточная ударная дрель LXT 18 В (XPH12Z, только инструмент) сочетает в себе мощность и время работы для выполнения большего количества задач по сверлению, завинчиванию и креплению в дереве, металле и каменной кладке.",
		image: "/img/products/drill1.png",
		price: 145,
		warranty: 12,
		origin: "Argentina",
		fav: true,
	},
	{
		id: "p2",
		title: "Угловая шлифовальная машина",
		brand: 'DEWALT 4.5"',
		description:
			"Малая угловая шлифовальная машина без фиксации оснащена мощным двигателем на 9 А с защитой от перегрузки для быстрого удаления материала, тонкой конструкцией шлифовальной машины диаметром 4,5 дюйма для повышения комфорта при длительном использовании и низкопрофильной конструкцией для работы в ограниченном пространстве.",
		image: "/img/products/grinder1.png",
		price: 89.99,
		warranty: 24,
		origin: "USA",
		fav: false,
	},
	{
		id: "p3",
		title: "Тачка",
		brand: "Garden Star",
		description:
			"The Yard Rover has a durable plastic, rust proof 5 cubic foot tray. The two air-filled tires, makes this Yard Rover easier to lift, balance and maneuver around the garden, lawn, barn, or farm. Suited to haul any items on most terrains",
		image: "/img/products/wheelbarrow1.png",
		price: 111.9,
		warranty: 6,
		origin: "Ireland",
		fav: false,
	},
	{
		id: "p4",
		title: "Пилка",
		brand: "Husqvarna",
		description:
			"Husqvarna 400 Series chainsaws are excellent all-around saws for outdoor projects, from tree-pruning to felling trees. Compact and versatile with innovative safety features, these gas-powered chainsaws are designed to maximize your cutting power and minimize fuel consumption.",
		image: "/img/products/chainsaw1.png",
		price: 449.99,
		warranty: 6,
		origin: "Ireland",
		fav: false,
	},
	{
		id: "p5",
		title: "Лопатка",
		brand: "Himutain",
		description:
			"Grab the shovel! This entrenching tool a collapsible spade used by military forces for a variety of military purposes. as well as survivalists, freedivers, campers, hikers and other outdoors groups.  Rust-resistance & anti-defamation, built to last long.",
		image: "/img/products/shovel1.png",
		price: 16.99,
		warranty: 1,
		origin: "Czech Republic",
		fav: false,
	},
	{
		id: "p6",
		title: "Отвертки",
		brand: "Ironcube",
		description:
			"MEET ALL YOUR NEEDS: This magnetic screwdriver kit includes 3 Phillips screwdrivers(Phillips 0 x 75mm, Phillips 1 x 75mm, Phillips 2 x 100mm) and 3 Flathead screwdrivers(Flathead 5 x 100mm, Flathead 3 x 100mm, Flathead 6 x 125mm).",
		image: "/img/products/screwdriver1.png",
		price: 9.99,
		warranty: 24,
		origin: "Colombia",
		fav: false,
	},

	{
		id: "p7",
		title: "Электрическая дрель",
		brand: "DrillMaster",
		description:
			"Мощная и надежная электрическая дрель, идеально подходит для всех домашних и профессиональных нужд. Включает в себя регулятор скорости для точного контроля.",
		image: "/img/products/electric-drill.png",
		price: 49.99,
		warranty: 12,
		origin: "США",
		fav: false,
	},
	{
		id: "p8",
		title: "Беспроводной молоток",
		brand: "HammerTech",
		description:
			"Аккумуляторный молоток, обеспечивающий высокую ударную силу, подходит для строительных и демонтажных работ. Идет в комплекте с перезаряжаемой литий-ионной батареей.",
		image: "/img/products/cordless-hammer.png",
		price: 99.99,
		warranty: 24,
		origin: "Германия",
		fav: false,
	},
	{
		id: "p9",
		title: "Циркулярная пила",
		brand: "SawIt",
		description:
			"Высокопроизводительная циркулярная пила с регулируемой глубиной и углом реза, предназначенная для точной резки дерева и других материалов.",
		image: "/img/products/circular-saw.png",
		price: 119.99,
		warranty: 24,
		origin: "Китай",
		fav: false,
	},
	{
		id: "p10",
		title: "Угловая шлифмашина",
		brand: "GrindPro",
		description:
			"Прочная угловая шлифмашина с мощным двигателем и функцией блокировки безопасности, идеально подходит для работ по металлу и камню.",
		image: "/img/products/angle-grinder.png",
		price: 89.99,
		warranty: 24,
		origin: "Италия",
		fav: false,
	},
	{
		id: "p11",
		title: "Лобзик",
		brand: "PuzzleCutter",
		description:
			"Эргономичный инструмент лобзик с несколькими вариантами лезвий и орбитальными настройками для резки сложных форм и узоров.",
		image: "/img/products/jigsaw.png",
		price: 79.99,
		warranty: 18,
		origin: "Канада",
		fav: false,
	},
	{
		id: "p12",
		title: "Стационарная пила",
		brand: "CutRight",
		description:
			"Профессиональная стационарная пила с расширенным столом и системой сбора пыли, обеспечивает точные прямые резы.",
		image: "/img/products/table-saw.png",
		price: 299.99,
		warranty: 36,
		origin: "Швеция",
		fav: false,
	},
	{
		id: "p13",
		title: "Шлифовальная машина",
		brand: "SmoothSurface",
		description:
			"Шлифовальная машина с переменной скоростью и эффективной системой сбора пыли, разработанная для гладкой обработки дерева и пластиков.",
		image: "/img/products/sander.png",
		price: 59.99,
		warranty: 12,
		origin: "США",
		fav: false,
	},
	{
		id: "p14",
		title: "Набор гаечных ключей",
		brand: "BoltMaster",
		description:
			"Полный набор гаечных ключей различных размеров, изготовленных из высокопрочной стали, подходит для автомобильного и промышленного использования.",
		image: "/img/products/wrench-set.png",
		price: 34.99,
		warranty: 24,
		origin: "Япония",
		fav: false,
	},
	{
		id: "p15",
		title: "Покрасочный аппарат",
		brand: "PaintPro",
		description:
			"Покрасочный аппарат с высокой вместимостью и регулируемым соплом, обеспечивающий гладкое и равномерное покрытие для профессиональных результатов.",
		image: "/img/products/paint-sprayer.png",
		price: 149.99,
		warranty: 24,
		origin: "Италия",
		fav: false,
	},
	{
		id: "p16",
		title: "Сварочный аппарат",
		brand: "WeldKing",
		description:
			"Компактный сварочный аппарат с продвинутыми функциями управления для TIG и MIG сварки, подходит как для профессионалов, так и для любителей.",
		image: "/img/products/welding-machine.png",
		price: 499.99,
		warranty: 60,
		origin: "Германия",
		fav: false,
	},
];

export default DUMMY_LIST;
