const DUMMY_LIST = [
  {
    id: "p1",
    title: "Дрель",
    brand: "Makita 18v",
    description:
      "Makita является инновационным лидером в области технологий бесщеточных двигателей, а бесщеточная ударная дрель LXT 18 В (XPH12Z, только инструмент) сочетает в себе мощность и время работы для выполнения большего количества задач по сверлению, завинчиванию и креплению в дереве, металле и каменной кладке.",
    image: "/img/products/drill1.png",
    price: 145,
    warranty: 12,
    origin: "Argentina",
    fav: true,
  },
  {
    id: "p2",
    title: "Угловая шлифовальная машина",
    brand: 'DEWALT 4.5"',
    description:
      "Малая угловая шлифовальная машина без фиксации оснащена мощным двигателем на 9 А с защитой от перегрузки для быстрого удаления материала, тонкой конструкцией шлифовальной машины диаметром 4,5 дюйма для повышения комфорта при длительном использовании и низкопрофильной конструкцией для работы в ограниченном пространстве.",
    image: "/img/products/grinder1.png",
    price: 89.99,
    warranty: 24,
    origin: "USA",
    fav: false,
  },
  {
    id: "p3",
    title: "Тачка",
    brand: "Garden Star",
    description: "The Yard Rover has a durable plastic, rust proof 5 cubic foot tray. The two air-filled tires, makes this Yard Rover easier to lift, balance and maneuver around the garden, lawn, barn, or farm. Suited to haul any items on most terrains",
    image: "/img/products/wheelbarrow1.png",
    price: 111.9,
    warranty: 6,
    origin: "Ireland",
    fav: false,
  },
  {   
    id: "p4",
    title: "Пилка",
    brand: "Husqvarna",
    description: "Husqvarna 400 Series chainsaws are excellent all-around saws for outdoor projects, from tree-pruning to felling trees. Compact and versatile with innovative safety features, these gas-powered chainsaws are designed to maximize your cutting power and minimize fuel consumption.",
    image: "/img/products/chainsaw1.png",
    price: 449.99,
    warranty: 6,
    origin: "Ireland",
    fav: false,
  },
  {
    id: "p5",
    title: "Лопатка",
    brand: "Himutain",
    description: "Grab the shovel! This entrenching tool a collapsible spade used by military forces for a variety of military purposes. as well as survivalists, freedivers, campers, hikers and other outdoors groups.  Rust-resistance & anti-defamation, built to last long.",
    image: "/img/products/shovel1.png",
    price: 16.99,
    warranty: 1,
    origin: "Czech Republic",
    fav: false,
  },
  {
    id: "p6",
    title: "Отвертки",
    brand: "Ironcube",
    description: "MEET ALL YOUR NEEDS: This magnetic screwdriver kit includes 3 Phillips screwdrivers(Phillips 0 x 75mm, Phillips 1 x 75mm, Phillips 2 x 100mm) and 3 Flathead screwdrivers(Flathead 5 x 100mm, Flathead 3 x 100mm, Flathead 6 x 125mm).",
    image: "/img/products/screwdriver1.png",
    price: 9.99,
    warranty: 24,
    origin: "Colombia",
    fav: false,
  },
];

export default DUMMY_LIST;
